cmd: 'python train.py'

hparams:
  model: ['res101', 'ResNeSt101', 'ResNeSt200', 'iResNet101', 'EfficientNet-B5']
  epochs: [5, 10]
  batch_size: [8, 16, 24]
  scale: [256, 320, 480]
  lr: [0.0001, 0.0002]

